openapi: 3.0.0
info:
  title: API de Controle de Tarefas
  version: 1.0.0
  description: |
    API RESTful para gerenciar tarefas (CRUD) com autenticação JWT.
    
    **Fluxo:**
    1. Registre um usuário em `/auth/register`.
    2. Faça login em `/auth/login` para obter um token JWT.
    3. Use o token no header `Authorization: Bearer <token>` para acessar as rotas protegidas de tarefas.
servers:
  - url: http://localhost:3000/api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TarefaInput:
      type: object
      properties:
        titulo:
          type: string
          example: "Comprar pão"
        descricao:
          type: string
          example: "Ir à padaria às 8h"
        concluida:
          type: boolean
          example: false
    UsuarioInput:
      type: object
      properties:
        email:
          type: string
          example: "usuario@exemplo.com"
        senha:
          type: string
          example: "123456"
paths:
  /auth/register:
    post:
      summary: Registrar novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioInput'
      responses:
        '201':
          description: Usuário registrado
        '400':
          description: Email já cadastrado ou dados inválidos
  /auth/login:
    post:
      summary: Login do usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioInput'
      responses:
        '200':
          description: Token JWT gerado
          content:
            application/json:
              example:
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        '401':
          description: Credenciais inválidas
  /tarefas:
    get:
      summary: Lista todas as tarefas
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de tarefas
          content:
            application/json:
              example:
                - id: 1
                  titulo: "Comprar pão"
                  descricao: "Ir à padaria às 8h"
                  concluida: false
    post:
      summary: Cria uma nova tarefa
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TarefaInput'
      responses:
        '201':
          description: Tarefa criada
  /tarefas/{id}:
    get:
      summary: Busca uma tarefa pelo ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tarefa encontrada
        '404':
          description: Tarefa não encontrada
    put:
      summary: Atualiza uma tarefa
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TarefaInput'
      responses:
        '200':
          description: Tarefa atualizada
        '404':
          description: Tarefa não encontrada
    delete:
      summary: Remove uma tarefa
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tarefa removida
        '404':
          description: Tarefa não encontrada 